# Generated by Django 3.2 on 2024-02-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'Настольная игра', 'verbose_name_plural': 'Настольные игры'},
        ),
        migrations.AlterModelOptions(
            name='genreboardgame',
            options={'verbose_name': 'Жанры настольной игры', 'verbose_name_plural': 'Жанры настольных игр'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='players',
            new_name='count_players',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_games', to='life.profile', verbose_name='Владелец'),
        ),
    ]
