# Generated by Django 4.2.10 on 2024-02-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20240207_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='life.profile', verbose_name='Друзья'),
        ),
    ]
