# Generated by Django 3.2 on 2024-02-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20240207_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSocialCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_life_profile_friends_+', to='life.Profile', verbose_name='Друзья'),
        ),
        migrations.CreateModel(
            name='SocialCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('members', models.ManyToManyField(blank=True, related_name='social_circles', through='life.ParticipantSocialCircle', to='life.Profile', verbose_name='Участники')),
            ],
        ),
        migrations.AddField(
            model_name='participantsocialcircle',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='life.profile', verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='participantsocialcircle',
            name='social_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_social_circles', to='life.socialcircle', verbose_name='Круг общения'),
        ),
    ]
