# Generated by Django 4.2.10 on 2024-02-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_alter_profile_friends'),
        ('life', '0003_auto_20240208_2244'),
    ]

    operations = [
    ]
