# Generated by Django 4.2.10 on 2024-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='avatar/', verbose_name='Аватар'),
        ),
    ]
