# Generated by Django 4.2.10 on 2024-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['-name'], 'verbose_name': 'Настольная игра', 'verbose_name_plural': 'Настольные игры'},
        ),
    ]
